name: Test, and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Verify types
        run: bun run format:check

      - name: Linter
        run: bun run lint

      - name: Knip
        run: bun run knip

      - name: Knip
        run: bun run check-duplication

      - name: Migrate database
        run: bun run db:migrate
        env:
          TURSO_DATABASE_URL: ${{ vars.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
