name: Test, and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: copy envfile
        run: cp .env.example .env

      - name: Install dependencies
        run: bun install

      - name: Verify types
        run: bun run format:check

      - name: Linter
        run: bun run lint

      - name: Knip
        run: bun run knip

      - name: Knip
        run: bun run check-duplication

      - name: Migrate database
        run: bun run db:migrate
